name = "cloudx-official"
compatibility_date = "2024-11-02"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
workers_dev = true

# Add your custom domain if you have one
# [env.production]
# routes = ["your-domain.com/*"]